version: "3.5"
services:
  mirai:
    image: openjdk:8-jre-alpine
    expose:
      - "8081"
    volumes:
      - "/root/mirai:/root/mirai"
    networks:
      - net
    command: ["/bin/sh", "/root/mirai/run.sh"]

  qbot:
    build:
      context: ./build
    env_file: bot.env
    working_dir: /root/mirai_bot
    environment:
      - host=mirai
      - port=8081
    volumes:
      - ".:/root/mirai_bot"
    depends_on:
      - mirai
    networks:
      - net
    command: python3 /root/mirai_bot/run.py

networks:
  net:
