version: "3.5"
services:
  mirai_console:
    image: openjdk:8-jre-alpine
    expose:
      - ${port}
    volumes:
      - ${mirai_path}:/root/mirai_console
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - net
    working_dir: /root/mirai_console
    command: ["/bin/sh","-c","java -jar mirai-console-wrapper-${wrapper_version}.jar << EOF
\nlogin ${qq} `echo ${password}|base64 -d`
\nEOF"]

  bot:
    build:
      context: ./build
    environment:
      host: mirai_console
      qq: ${qq}
      port: ${port}
      authKey: ${authKey}
    env_file: bot.env
    volumes:
      - .:/root/mirai_bot
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mirai_console
    restart: unless-stopped
    networks:
      - net
    working_dir: /root/mirai_bot
    command: python3 run.py

networks:
  net:
