version: "3.5"
services:
  mirai:
    image: openjdk:8-jre-alpine
    expose:
      - "8081"
    volumes:
      - "/root/mirai:/root/mirai"
    networks:
      - net
    command: ["/bin/sh", "/root/mirai/run.sh"]

  qbot:
    build:
      context: ./build
    environment:
      - host=mirai
      - port=8081
      - qq=123456
      - authKey=qwerty1234
      - setu_apikey=
    volumes:
      - ".:/root/qbot"
    depends_on:
      - mirai
    networks:
      - net
    command: python3 -m /root/qbot/run.py

networks:
  net: